"""tasks table update

Revision ID: 33b3dc178ac4
Revises: 8a6267dcec7d
Create Date: 2021-05-29 12:50:09.899754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33b3dc178ac4'
down_revision = '8a6267dcec7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_task_timestamp'), 'task', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_timestamp'), table_name='task')
    op.drop_column('task', 'timestamp')
    # ### end Alembic commands ###
